### PR TITLE
Issue #3: Added fixable functionality to rule

### PR DESCRIPTION
**Pull request by joshuatvernon**
https://github.com/fxOne/eslint-plugin-sort-keys-shorthand/issues/3

### CODE REVIEW

**Comment by joshuatvernon** [comment]
This appeared to work 🤷‍♂️ I think you should have a look though before merging. I tested it against my code base and it was able to fix 700/750 errors

**Comment by fxOne** [comment]
Thanks for PR. 

But you cannot autofix this rule as it may change the program execution, see also: https://github.com/eslint/eslint/issues/7714

But I think the suggestion API would be a solution for this problem: https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions
If you can rewrite it and add some tests I would like to merge the PR.

**Comment by lougreenwood** [comment]
@joshuatvernon Do you have any thoughts on converting this into code actions / suggestions instead of an auto-fix as @fxOne mentioned above?

**Comment by joshuatvernon** [comment]
Mmhmm it sounds like it would be a good idea. If you want to take a look feel free and I'm happy to review. I haven't been developing in JS for a little while and the previous project I was on got this working locally.

**Pull request closed without merging**
